from .register import register
from .home import home
from .mylogin import mylogin
from .profile import profile
from .entekhabVahed import entekhabVahed
from .mylogout import mylogout
from .choiceCourse import choiceCourse
from .deleteCourse import deleteCourse
from .menu import menu
from .amozesh import amozesh
from .setgrades import setgrades
from .hometeacher import hometeacher
from .registerCourse import registerCourse
